### ISSUE TITLE
Vendor Python prompt toolkit

### ISSUE THREAD

**Issue by pbugnion** [ASIDataScience/sml-sync#14]
Depending on branch 2.0 of Python prompt toolkit makes *sml-sync* less stable (since we have no guarantees about backwards compatibility of changes) and harder to install. The easiest fix is probably to vendor Python prompt toolkit and distribute it as part of sml-sync for now.

Happy to hear other suggestions.

**Comment by pbugnion** [comment]
This may be moot -- Prompt toolkit 2.0 just got merged.

**Comment by janfreyberg** [comment]
That's great news!

**Comment by pbugnion** [comment]
I was a bit worried that our custom installation would be broken now that branch 2.0 of python prompt toolkit doesn't exist any more, but everything seems to work. It just pulls version `2.0.1` from pypi.

**Comment by janfreyberg** [comment]
Great! Do you know if ipython has been updated to use the new prompt toolkit? I think k ipython breaking was a common pain point but if it still depends on <2.0 then we will still have to recommend a virtual environment...

**Comment by srstevenson** [comment]
Perhaps packaging sml-sync as a ZIP archive (see [PEP 441](https://www.python.org/dev/peps/pep-0441/)) would allow sml-sync to be run from a virtual environment with IPython and prompt_toolkit < 2.0 already installed, without breaking them?

Also, [Buck](https://buckbuild.com/) and [Pants](https://www.pantsbuild.org/) (Facebook and Twitter's respective clones of Google's Bazel build tool) allow you to build [PEX files](https://github.com/pantsbuild/pex), which are effectively hermetic, relocatable virtual environments. Either Buck or Pants is a very large new dev dependency though.

**Comment by pbugnion** [comment]
Thanks for that -- very useful.

I've opened a issue #20  about allowing sml-sync and IPython to coexist in an environment with those suggestions. Closing this now.
