### ISSUE TITLE
Ensure sml-sync can coexist with IPython in a Python environment

### ISSUE THREAD

**Issue by pbugnion** [ASIDataScience/sml-sync#20]
At the moment, sml-sync requires prompt toolkit version 2, but IPython relies on version 1 of prompt toolkit. These are incompatible, so installing sml-sync typically leads to an upgrade of prompt toolkit, which, in turn, breaks IPython.

An obvious fix is to run sml-sync in a dedicated virtual environment (I think this can be handled automatically using pipsi). This is painful for users who don't use the virtual environment mechanism.

As alternatives:
1. vendor prompt toolkit and import from vendored directories
2. packaging as a zip archive (see [PEP 441](https://www.python.org/dev/peps/pep-0441/) and [docs](https://docs.python.org/3/library/zipapp.html#creating-standalone-applications-with-zipapp)) -- thanks Scott for the idea
3. [pants](https://www.pantsbuild.org/why_use_pants.html) looks like it would help, but at the cost of introducing a build took that we are unfamiliar with.
4. Do nothing and recommend using pipsi for the installation.

I think my preferences are 2., then investigate how difficult 3. is to set up, then 1., but happy with whatever.

**Comment by srstevenson** [comment]
IPython has now migrated to `prompt_toolkit` 2: https://github.com/ipython/ipython/pull/11177.

**Comment by janfreyberg** [comment]
yeah, this has been resolved for a while now
