### ISSUE TITLE
Differences screen should order files by size and show size

### ISSUE THREAD

**Issue by pbugnion** [ASIDataScience/sml-sync#4]
At the moment, the differences screen is of limited use if you have lots of files. To make it more useful, we should rank files by size, in descending order and show more information for each file: when it was last modified, the local and remote size where appropriate etc. We should also allow scrolling so you can see every file.

This was originally reported by Tom Begley in a private message to me (Pascal).

**Comment by janfreyberg** [comment]
Nice idea @tcbegley!

**Comment by pbugnion** [comment]
Merged in PR #5 and released in 0.3.0.
